name: Build & Test Backgammon

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test .NET + Frontend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: backgammon_netcore_db
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DOTNET_VERSION: '9.x'
      ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=backgammon_netcore_db;Username=postgres;Password=postgres"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore Backgammon.sln

      - name: Build solution
        run: dotnet build Backgammon.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test Backgammon.Tests/Backgammon.Tests.csproj --verbosity detailed --configuration Release

      - name: Setup Node.js (for frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build